services:
  db:
    image: mysql-todo
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: "--mysql_native_password=ON"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  web:
    image: nodejs-todo
    environment:
      - DB_HOST=db
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=test_db
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

